name: Run Unit Tests

on:
  push:
    branches:
      - main
      - develop
      - '**' # optional: match all branches
  pull_request: # optional: runs on PRs too

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # or your preferred Node.js version

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn test:coverage

      - name: Generate Coverage Badge
        uses: davelosert/jest-coverage-report-action@v2
        with:
          coverage-file: coverage/coverage-summary.json
          badge-directory: .github/badges

      - name: Commit coverage badge if changed
        uses: EndBug/add-and-commit@v9
        with:
          add: '.github/badges/coverage.svg'
          message: 'chore: update coverage badge'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Job status
        run: echo "This job's status is ${{ job.status }}."